// EDIT THIS FILE to add your 30 photos of her and her bestie, with captions.
// Add your images to assets/photos/bestie/ and write a short caption for each.

const bestieGallery = [
  { src: "assets/photos/bestie/pic-01.jpg", caption: "2019 April. While mounica and I were doing our visual communication Assigment" },
  { src: "assets/photos/bestie/pic-02.jpg", caption: "The first time I went to port Stanley with Mounica. 2019" },
  { src: "assets/photos/bestie/pic-03.jpg", caption: "Second time we went to port Stanley - December 2019 after our college and graduation" },
  { src: "assets/photos/bestie/pic-04.jpg", caption: "My birthday January 2020" },
  { src: "assets/photos/bestie/pic-05.jpg", caption: "We went to a safari. African lion safari if Im not wrong. June 2020" },
  { src: "assets/photos/bestie/pic-06.jpg", caption: "Mounicas fav pic of ours" },
  { src: "assets/photos/bestie/pic-07.jpg", caption: "Strawberry picking June 2020" },
  { src: "assets/photos/bestie/pic-08.jpg", caption: "When Ram and Lakshman came home - July 2020" },
  { src: "assets/photos/bestie/pic-09.jpg", caption: "My fav pic of ours - August 2020. We went to a sunflower farm." },
  { src: "assets/photos/bestie/pic-10.jpg", caption: "We went to a lake - kettle and stoney point, where Mounica got inside the water and chilled for a bit." },
  { src: "assets/photos/bestie/pic-11.jpg", caption: "When we went camping - August 2020" },
  { src: "assets/photos/bestie/pic-12.jpg", caption: "Our first snow man togther dec 2020" },
  { src: "assets/photos/bestie/pic-13.jpg", caption: "Jan 2020 when mouni moved into her new apartment" },
  { src: "assets/photos/bestie/pic-14.jpg", caption: "Our Sunday coffee and fritters from the market." },
  { src: "assets/photos/bestie/pic-15.jpg", caption: "Our long distance calls" },
  { src: "assets/photos/bestie/pic-16.jpg", caption: "Our Montreal trip!!" },
  { src: "assets/photos/bestie/pic-17.jpg", caption: "2019 summer - behind the Naigara falls" },
  { src: "assets/photos/bestie/pic-18.jpg", caption: "Same - strawberry picking" },
  { src: "assets/photos/bestie/pic-19.jpg", caption: "Montreal" },
  { src: "assets/photos/bestie/pic-20.jpg", caption: "Us baking - long distance" },
  { src: "assets/photos/bestie/pic-21.jpg", caption: "Us at an event 2019" },
  { src: "assets/photos/bestie/pic-22.jpg", caption: "Me buying her post cards wherever I go" },
  { src: "assets/photos/bestie/pic-23.jpg", caption: "When she came to chennai - 2024" },
  { src: "assets/photos/bestie/pic-24.jpg", caption: "I got her flowers" },
  { src: "assets/photos/bestie/pic-25.jpg", caption: "Van Gogh- chennai Feb 2024" },
  { src: "assets/photos/bestie/pic-26.jpg", caption: "Her and thamizh." },
  { src: "assets/photos/bestie/pic-27.jpg", caption: "Chennai auto rides" },
  { src: "assets/photos/bestie/pic-28.jpg", caption: "Our lunch dates in chennai 2024" },
  { src: "assets/photos/bestie/pic-29.jpg", caption: "Hayee" },
  { src: "assets/photos/bestie/pic-30.jpg", caption: "That sums US ♥️♥️♥️" },
  { src: "assets/photos/bestie/pic-31.jpg", caption: "This when I went back in 2024. Got her cream bun from iyengar bakery Bangalore - took it all the way for her" },
  { src: "assets/photos/bestie/pic-32.jpg", caption: "Shruti gift her a dyson!!" },
  { src: "assets/photos/bestie/pic-33.jpg", caption: "Us revisiting the market" },
  { src: "assets/photos/bestie/pic-34.jpg", caption: "Our skin care routines" },
  { src: "assets/photos/bestie/pic-35.jpg", caption: "Second time I cut her hair 🤣" },
  { src: "assets/photos/bestie/pic-36.jpg", caption: "Our thrift store day out" },
  { src: "assets/photos/bestie/pic-37.jpg", caption: "We made enchi posina pappu potato fry and sat and ate in the balcony" },
  { src: "assets/photos/bestie/pic-38.jpg", caption: "When she took me to the most amazing bar in town, she knows it" },
  { src: "assets/photos/bestie/pic-39.jpg", caption: "Pottery class - as my bachelorette party" },
  { src: "assets/photos/bestie/pic-40.jpg", caption: "And then I left 😭😭" },
  { src: "assets/photos/bestie/pic-41.jpg", caption: "My haldi" },
  { src: "assets/photos/bestie/pic-42.jpg", caption: "Very Closssseeeeee" }
];