// EDIT THIS FILE to add your 30 photos of her and her bestie, with captions.
// Add your images to assets/photos/bestie/ and write a short caption for each.

const bestieGallery = [
  { src: "assets/photos/bestie/pic-01.jpg", caption: "2019 April. While mounica and I were doing our visual communication Assigment" },
  { src: "assets/photos/bestie/pic-02.jpg", caption: "The first time I went to port Stanley with Mounica. 2019" },
  { src: "assets/photos/bestie/pic-03.jpg", caption: "Second time we went to port Stanley - December 2019 after our college and graduation" },
  { src: "assets/photos/bestie/pic-04.jpg", caption: "My birthday January 2020" },
  { src: "assets/photos/bestie/pic-05.jpg", caption: "We went to a safari. African lion safari if I’m not wrong. June 2020" },
  { src: "assets/photos/bestie/pic-06.jpg", caption: "Mounicas fav pic of ours" },
  { src: "assets/photos/bestie/pic-07.jpg", caption: "Strawberry picking June 2020" },
  { src: "assets/photos/bestie/pic-08.jpg", caption: "When Ram and Lakshman came home - July 2020" },
  { src: "assets/photos/bestie/pic-09.jpg", caption: "Replace with your own caption" },
  { src: "assets/photos/bestie/pic-10.jpg", caption: "Replace with your own caption" },
  { src: "assets/photos/bestie/pic-11.jpg", caption: "Replace with your own caption" },
  { src: "assets/photos/bestie/pic-12.jpg", caption: "Replace with your own caption" },
  { src: "assets/photos/bestie/pic-13.jpg", caption: "Replace with your own caption" },
  { src: "assets/photos/bestie/pic-14.jpg", caption: "Replace with your own caption" },
  { src: "assets/photos/bestie/pic-15.jpg", caption: "Replace with your own caption" },
  { src: "assets/photos/bestie/pic-16.jpg", caption: "Replace with your own caption" },
  { src: "assets/photos/bestie/pic-17.jpg", caption: "Replace with your own caption" },
  { src: "assets/photos/bestie/pic-18.jpg", caption: "Replace with your own caption" },
  { src: "assets/photos/bestie/pic-19.jpg", caption: "Replace with your own caption" },
  { src: "assets/photos/bestie/pic-20.jpg", caption: "Replace with your own caption" },
  { src: "assets/photos/bestie/pic-21.jpg", caption: "Replace with your own caption" },
  { src: "assets/photos/bestie/pic-22.jpg", caption: "Replace with your own caption" },
  { src: "assets/photos/bestie/pic-23.jpg", caption: "Replace with your own caption" },
  { src: "assets/photos/bestie/pic-24.jpg", caption: "Replace with your own caption" },
  { src: "assets/photos/bestie/pic-25.jpg", caption: "Replace with your own caption" },
  { src: "assets/photos/bestie/pic-26.jpg", caption: "Replace with your own caption" },
  { src: "assets/photos/bestie/pic-27.jpg", caption: "Replace with your own caption" },
  { src: "assets/photos/bestie/pic-28.jpg", caption: "Replace with your own caption" },
  { src: "assets/photos/bestie/pic-29.jpg", caption: "Replace with your own caption" },
  { src: "assets/photos/bestie/pic-30.jpg", caption: "The bestie era, forever" },
];